name: CI Процесс
on:
  push:
    branches: [develop, release/*]
  pull_request:
    branches: [develop, release/*]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JDK 17 Тохируулах
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Checkstyle validate phase-д автоматаар явна, тиймээс шууд clean verify хангалттай
      - name: Build + Tests + JaCoCo Check
        run: mvn -B clean verify

      # (Сонголт) тайланг artifact болгохыг хүсвэл:
      - name: Generate JaCoCo HTML report
        run: mvn -B jacoco:report
